version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - leilao-net

  app:
    build: .
    # Mapeia a porta 5000 do container para a 5000 do seu PC
    ports:
      - "5000:5000"
    # Vari√°veis de ambiente
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./app:/app/app
    depends_on:
      - redis
    networks:
      - leilao-net

networks:
  leilao-net: