apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app # Nome do deployment no flask-deployment.yaml
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50 # Se passar de 50% de CPU, cria novos pods
